name: Publish Packages

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_PATH: https://nuget.pkg.github.com/jafin/index.json

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET Core 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Add private GitHub registry to NuGet
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github ${{ env.NUGET_PATH }}

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish FluentEmail.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/FluentEmail.Core/FluentEmail.Core.csproj
          #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: ${{ env.NUGET_PATH }}
          INCLUDE_SYMBOLS: true
    - name: Publish FluentEmail.Smtp
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Senders/FluentEmail.Smtp/FluentEmail.Smtp.csproj
          #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: ${{ env.NUGET_PATH }}
          INCLUDE_SYMBOLS: true
    - name: Publish FluentEmail.Sendgrid
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Senders/FluentEmail.SendGrid/FluentEmail.SendGrid.csproj
          #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: ${{ env.NUGET_PATH }}
          INCLUDE_SYMBOLS: true
    #- name: Publish FluentEmail.MailTrap
    #  uses: brandedoutcast/publish-nuget@v2.5.2
    #  with:
    #      PROJECT_FILE_PATH: src/Senders/FluentEmail.Mailtrap/FluentEmail.Mailtrap.csproj
    #      NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #      NUGET_SOURCE: ${{ env.NUGET_PATH }}
    - name: Publish FluentEmail.MailKit
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Senders/FluentEmail.MailKit/FluentEmail.MailKit.csproj
          #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: ${{ env.NUGET_PATH }}
          INCLUDE_SYMBOLS: true
    - name: Publish FluentEmail.Mailgun
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Senders/FluentEmail.Mailgun/FluentEmail.Mailgun.csproj
          #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: ${{ env.NUGET_PATH }}
          INCLUDE_SYMBOLS: true
    - name: Publish FluentEmail.Razor
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Renderers/FluentEmail.Razor/FluentEmail.Razor.csproj
          #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: ${{ env.NUGET_PATH }}
          INCLUDE_SYMBOLS: true
    - name: Publish FluentEmail.Liquid
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Renderers/FluentEmail.Liquid/FluentEmail.Liquid.csproj
          #NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: ${{ env.NUGET_PATH }}
          INCLUDE_SYMBOLS: true
    # This is currently maintained separately
    #- name: Publish FluentEmail.Graph
    #  uses: brandedoutcast/publish-nuget@v2.5.2
    #  with:
    #      PROJECT_FILE_PATH: src/Senders/FluentEmail.Graph/FluentEmail.Graph.csproj
    #      NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #      NUGET_SOURCE: ${{ env.NUGET_PATH }}
